# HUSTOJ Java Configuration
# Database
db.host=localhost
db.name=jol
db.user=hustoj
db.password=OostHD0YYXi2UfY2AsmKONCBJnHC6B

# System
oj.name=HUSTOJ
oj.home=/
oj.admin=root@localhost
oj.data=/home/judge/data

# Features
oj.lang=cn
oj.sim=false
oj.online=false
oj.dict=false
oj.ace.editor=true
oj.auto.share=false
oj.css=white.css
oj.vcode=false
oj.register=true
oj.mail=false
oj.printer=false
oj.appendcode=true
oj.ce.penalty=false
oj.oi.mode=false
oj.sae=false

# UDP Judge
oj.udp=true
oj.udp.server=127.0.0.1
oj.udp.port=1536
oj.judge.hub.path=../judge

# Template
oj.template=syzoj

# Login
oj.login.mod=hustoj
oj.reg.need.confirm=false
oj.email.confirm=false
oj.expiry.days=365
oj.need.login=false
oj.login.fail.limit=5
oj.long.login=false
oj.keep.time=30

# Contest
oj.rank.lock.percent=0
oj.rank.lock.delay=3600
oj.show.metal=true
oj.contest.rank.fix.header=false
oj.noip.keyword=noip

# Submit
oj.submit.cooldown.time=10
oj.benchmark.mode=false
oj.public.status=true

# Misc
oj.share.code=false
oj.recent.contest=false
oj.blockly=false
oj.markdown=marked.js
oj.mathjax=true
oj.fancy.result=false
oj.fancy.mp3=http://cdn.hustoj.com/mp3.php
oj.lang.mask=33554356
